brokerClusterName=DefaultCluster
brokerName=broker-a
brokerId=0
deleteWhen=04
fileReservedTime=48
brokerRole=ASYNC_MASTER
flushDiskType=ASYNC_FLUSH

# Listen on all interfaces
brokerIP1=0.0.0.0

# Auto create topic
autoCreateTopicEnable=true

# Topic settings
autoCreateSubscriptionGroup=true
